In [4]:
import pandas as pd
import sys
project_root = "/Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent"
if project_root not in sys.path:
    sys.path.append(project_root)

%run /Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent/common/constants.py
%run /Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent/common/helpers.py
%run /Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent/common/utils.py

In [5]:
import sqlite3
import pandas as pd

db_path = "/Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent/data/database/system.db"
conn = sqlite3.connect(db_path)

In [6]:
query = "SELECT * FROM sqlite_master WHERE type='table';"
pd.read_sql(query, conn)

,type,name,tbl_name,rootpage,sql
0,table,users,users,2,CREATE TABLE users (\n user...
1,table,genres,genres,4,CREATE TABLE genres (\n gen...
2,table,sqlite_sequence,sqlite_sequence,6,"CREATE TABLE sqlite_sequence(name,seq)"
3,table,authors,authors,7,CREATE TABLE authors (\n au...
4,table,books,books,9,CREATE TABLE books (\n book...
5,table,book_authors,book_authors,10,CREATE TABLE book_authors (\n ...
6,table,book_genres,book_genres,12,CREATE TABLE book_genres (\n ...
7,table,user_genres,user_genres,14,CREATE TABLE user_genres (\n ...
8,table,interactions,interactions,16,CREATE TABLE interactions (\n ...
9,table,ratings,ratings,17,CREATE TABLE ratings (\n us...

In [7]:
query = "SELECT * FROM users where user_id = 'sayali_moghe';"
pd.read_sql(query, conn)

,user_id,name,created_at,login_attempt,last_login
0,sayali_moghe,Sayali Moghe,2026-02-01T01:22:43.414735,27,2026-02-15T16:30:56.779607

In [19]:
query = "SELECT * FROM books where title = 'The Fault in Our Stars';"
pd.read_sql(query, conn)

,book_id,title,description,infolink,created_at
0,140091,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,https://www.goodreads.com/book/show/11870085-t...,2026-02-15T17:41:04.595245

In [11]:
query = "SELECT * FROM authors WHERE name LIKE '%Lesley Stanfield%';"
pd.read_sql(query, conn)

   author_id                              name
0      64381                  Lesley Stanfield
1      64382  Lesley StanfieldMelody Griffiths

In [ ]:
query = "SELECT * FROM books b INNER JOIN book_authors ba ON b.book_id = ba.book_id WHERE ba.author_id = 54708;"
pd.read_sql(query, conn)

,book_id,title,description,infolink,created_at,book_id,author_id
0,3748,Dragons Stained Glass Coloring Book (Dover Sta...,Create a bit of medieval magic by coloring 8 a...,http://books.google.nl/books?id=ABhIXsWd2mwC&d...,2026-01-31 23:24:20,3748,54708
1,4701,The Great Racehorses,Thirty famous champions of the thoroughbred ra...,http://books.google.nl/books?id=56C0CwAAQBAJ&d...,2026-01-31 23:24:20,4701,54708
2,15542,The big book of horses,Colorists and horse lovers of all ages will tr...,http://books.google.com/books?id=sKj42MI-lKcC&...,2026-01-31 23:24:20,15542,54708
3,25677,Life in a Medieval Castle and Village Coloring...,Illustrations depicting everyday life in the M...,http://books.google.com/books?id=ID8hIlPcM6UC&...,2026-01-31 23:24:20,25677,54708
4,30253,Donkeys Still Talk: Hearing God's Voice When Y...,Special edition slipcase edition of John Green...,http://books.google.com/books?id=MLacAgAAQBAJ&...,2026-01-31 23:24:20,30253,54708
5,52739,Wild Animals Stained Glass Coloring Book (Dove...,Create exciting stained glass pictures with 16...,http://books.google.com/books?id=xUNrSaEVQisC&...,2026-01-31 23:24:20,52739,54708
6,83772,A Passage To India (Turtleback School & Librar...,Bijna zes jaar na het overweldigende succes va...,https://play.google.com/store/books/details?id...,2026-01-31 23:24:20,83772,54708
7,93464,Super Snappy ABC: Pop Up Fun (This Is a Line E...,Special edition slipcase edition of John Green...,http://books.google.com/books?id=MLacAgAAQBAJ&...,2026-01-31 23:24:20,93464,54708
8,97445,Great Race Horses,Thirty famous champions of the thoroughbred ra...,http://books.google.com/books?id=56C0CwAAQBAJ&...,2026-01-31 23:24:20,97445,54708
9,140091,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,https://www.goodreads.com/book/show/11870085-t...,2026-02-15T17:41:04.595245,140091,54708
10,140092,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None,2026-02-15T18:21:34.483034,140092,54708
11,140093,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None,2026-02-15T18:24:29.745445,140093,54708
12,140094,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None,2026-02-15T18:27:32.693484,140094,54708
13,140095,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None,2026-02-15T18:30:23.564426,140095,54708

In [25]:
query = (
    "SELECT DISTINCT b.book_id, b.title, b.description, b.infolink "
    "FROM books b "
    "JOIN book_authors ba ON b.book_id = ba.book_id "
    "WHERE LOWER(b.title) LIKE LOWER('the fault in our stars') "
    "AND ba.author_id IN (54708)")
pd.read_sql(query, conn)

,book_id,title,description,infolink
0,140091,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,https://www.goodreads.com/book/show/11870085-t...
1,140092,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None
2,140093,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None
3,140094,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None
4,140095,The Fault in Our Stars,Despite the tumor-shrinking medical miracle th...,None

In [13]:
query = "SELECT * FROM books b INNER JOIN book_genres bg ON b.book_id = bg.book_id WHERE b.book_id = 24961;"
pd.read_sql(query, conn)

,book_id,title,description,infolink,created_at,book_id,genre_id
0,24961,The Encyclopedia of Knitting Techniques,Collects basic and advanced knitting technique...,http://books.google.com/books?id=CM5pcAAACAAJ&...,2026-01-31 23:24:20,24961,12

In [15]:
query = "SELECT * FROM genres WHERE genre_id = 12;"
pd.read_sql(query, conn)

   genre_id                name
0        12  crafts and hobbies

In [39]:
query = (
    "SELECT bg.book_id, COUNT(r.book_id) as rating_count "
    "FROM book_genres bg "
    "LEFT JOIN ratings r ON bg.book_id = r.book_id "
    "WHERE bg.genre_id = 23 "
    "GROUP BY bg.book_id "
    "ORDER BY rating_count DESC "
    "LIMIT 5"
)
pd.read_sql(query, conn)

   book_id  rating_count
0    27310          3415
1    21641          3345
2    87977          3280
3     9918          1626
4    45778          1448

In [40]:
query = "SELECT * FROM books b inner join book_genres bg on bg.book_id = b.book_id where b.book_id = 27310;"
pd.read_sql(query, conn)

,book_id,title,description,infolink,created_at,book_id,genre_id
0,27310,Harry Potter and The Sorcerer's Stone,Celebrate 20 years of Harry Potter magic! Harr...,http://books.google.com/books?id=HksgDQAAQBAJ&...,2026-01-31 23:24:20,27310,23

In [ ]:
# query = "UPDATE users set login_attempt = 0, last_login = null where user_id = 'sayali_moghe';"
cursor = conn.cursor()
cursor.execute(query)
conn.commit()
print(f"Rows updated: {cursor.rowcount}")
cursor.close()

Rows updated: 1

In [ ]:
# import pickle
# filename = "/Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent/data/model/best_model_params.pkl"
# data = {'alpha': 80, 'factors': 128, 'iterations': 15, 'random_state': 42, 'regularization': 0.2}
# with open(filename, "wb") as f:
#     pickle.dump(data, f)

In [ ]:
# data = {'candidate_pool_size':300, 'lambda':0.6}
# import pickle
# filename = "/Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent/data/model/best_rec_params.pkl"
# with open(filename, "wb") as f:
#     pickle.dump(data, f)

In [42]:
import pandas as pd
df = pd.read_feather("/Users/sayalimoghe/Documents/Career/GitHub/conversational-book-recommendation-agent/data/clean/cleaned_books_data.ftr")
df.head()

,book_id,title,authors,description,genres,infolink
0,1,Dr. Seuss: American Icon,[Philip Nel],Philip Nel takes a fascinating look into the k...,[biography and autobiography],http://books.google.nl/books?id=IjvHQsCn_pgC&d...
1,2,Wonderful Worship in Smaller Churches,[David R. Ray],This resource includes twelve principles in un...,[religion],http://books.google.nl/books?id=2tsDAAAACAAJ&d...
2,3,Whispers of the Wicked Saints,[Veronica Haddon],Julia Thomas finds her life spinning out of co...,[fiction],http://books.google.nl/books?id=aRSIgJlq6JwC&d...
3,4,The Church of Christ: A Biblical Ecclesiology ...,[Everett Ferguson],In The Church of Christ: A Biblical Ecclesiolo...,[religion],http://books.google.nl/books?id=kVqRaiPlx88C&d...
4,5,Saint Hyacinth of Poland,[Mary Fabyan Windeatt],The story for children 10 and up of St. Hyacin...,[biography and autobiography],http://books.google.nl/books?id=lmLqAAAACAAJ&d...

In [46]:
df[df["title"].str.contains("Tolkien", case=False, na=False)]

,book_id,title,authors,description,genres,infolink
1367,1368,Myth & Middle-Earth: Exploring the Medieval Le...,[Naomi Wolf],Explores the phenomenon of the violent backlas...,[social science],http://books.google.nl/books?id=OSC0AAAAIAAJ&d...
2167,2168,The Map of Tolkien's Middle-earth,[Brian Sibley],Includes four posters depicting Tolkien's worl...,[fiction],http://books.google.nl/books?id=gCENA64Y-O4C&d...
6572,6573,J. R. R. Tolkien - The Authorized Biography,[Humphrey Carpenter],"Carefully traces Tolkien's life, revealing sur...",[biography and autobiography],http://books.google.nl/books?id=JeXFmc90o7YC&d...
13622,13623,The Tolkien Reader,[John Ronald Reuel Tolkien],An invitation to Tolkien's world. This rich tr...,[other],http://books.google.nl/books?id=2yQeAQAAIAAJ&d...
14904,14905,Renaissance of wonder: The fantasy worlds of C...,[Marion Lochhead],"""A literary rebirth of wonder has produced an ...",[other],http://books.google.com/books?id=Nn9YAAAAYAAJ&...
32851,32852,Master of Middle Earth the Fiction of J.R.R. T...,[Paul Harold Kocher],A literary study of Tolkien's famous trilogy a...,[literary criticism],http://books.google.com/books?id=hR-oAAAAIAAJ&...
35485,35486,The People's Guide to J.R.R. Tolkien,[Theonering.Net (Firm)],"A fan-based exploration of Middle-earth, writt...",[literary criticism],http://books.google.com/books?id=1NNf8xYCntAC&...
36625,36626,Tolkien in the Land of Heroes : Discovering th...,[Anne C. Petty],Petty explores why J.R.R. Tolkien's works cont...,[literary criticism],http://books.google.com/books?id=GIpbAAAAMAAJ&...
40910,40911,War and the Works of J.R.R. Tolkien,[Janet Brennan Croft],Examines the role of war in Tolkien's life and...,[literary criticism],http://books.google.com/books?id=LHZlAAAAMAAJ&...
55864,55865,The J. R. R. Tolkien Audio Collection,"[Christopher Tolkien, John Ronald Reuel Tolkien]","For generations, J R R Tolkien's words have br...",[other],http://books.google.com/books?id=eaGEoAEACAAJ&...
58580,58581,Understanding Tolkien And The Lord Of The Rings,"[Neil D. Isaacs, Rose A. Zimbardo]",Selected essays on Tolkien's trilogy include W...,[literary criticism],http://books.google.com/books?id=GEWXQbASXZUC&...
62670,62671,TOLKIEN: A CRITICAL ASSESSMENT,[Michael D. C. Drout],"A detailed work of reference and scholarship, ...",[history],http://books.google.com/books?id=B0loOBA3ejIC&...
63732,63733,The Life and Work of J.R.R. Tolkien ( Critical...,[Michael White],Explores the life and career of the British fa...,[biography and autobiography],http://books.google.com/books?id=wpVrQgAACAAJ&...
78115,78116,Tolkien Criticism An Annotated Checklist Hardc...,"[Lloyd W. Currey, Marshall B. Tymn, Roger C. S...",Academic attention to science fiction and fant...,[literary criticism],https://play.google.com/store/books/details?id...
86518,86519,J.R.R. Tolkien and His Literary Resonances: Vi...,"[Sir George Clark, Sir]","Although Tolkien's literary works have, over t...",[literary criticism],http://books.google.nl/books?id=ES0Hs75IVg0C&d...
89109,89110,"Tolkien: Man and Myth, a Literary Life",[Joseph Pearce],J.R.R. Tolkien's The Lord of the Rings took fi...,[religion],http://books.google.nl/books?id=Q3hbAAAAMAAJ&d...
91297,91298,Tolkien and the Critics,"[Neil D. Isaacs, Rose A. Zimbardo]","Fifteen critical essays analyze the quality, s...",[other],http://books.google.com/books?id=UFjBAAAAIAAJ&...
102061,102062,A Tolkien Compass: Including J. R. R. Tolkien'...,"[Agnes Perkins, Charles Adolph Huttar, John Ro...","The structure, content, and character of Tolki...",[literary criticism],http://books.google.com/books?id=TqJ7gHrwjUEC&...
102590,102591,Realms of Tolkien: Images of Middle-earth,[J. R. R. Tolkien],Twenty new and familiar Tolkien artists are re...,[other],http://books.google.com/books?id=6lNmPwAACAAJ&...
107519,107520,Biography of J. R. R. Tolkien: Architect of Mi...,[Daniel Grotta],"John Ronald Reuel Tolkien (1892-1973), author ...",[biography and autobiography],http://books.google.com/books?id=4j4eAQAAIAAJ&...
109983,109984,The Two Towers: Part II of The Lord of the Rin...,[J.R.R. Tolkien],Begin your journey into Middle-earth... The in...,[young adult fiction],https://play.google.com/store/books/details?id...
110295,110296,TOLKIEN: The Illustrated Encyclopaedia,[David Day],Sections alphabetically list facts about the h...,[fiction],http://books.google.com/books?id=Nzh93npJTe4C&...
114169,114170,Tolkien and C.S. Lewis: The Gift of Friendship,[Colin Duriez],Reveals the complex friendship between the two...,[biography and autobiography],http://books.google.com/books?id=GQMwj9mcE-AC&...
123466,123467,Tolkien the Medievalist (Routledge Research in...,[Jane Chance],"Interdisciplinary in approach, Tolkien the Med...",[history],http://books.google.com/books?id=6TX3hJckf3YC&...
127327,127328,Tolkien,"[Meg Belviso, Pam Pollack, Who Hq]",An introduction to the life and career of the ...,[juvenile nonfiction],http://books.google.com/books?id=hgs4DwAAQBAJ&...
127685,127686,"The Individuated Hobbit: Jung, Tolkien and the...",[Timothy R. O'Neill],Shows that the Lord of the Rings can be read i...,[other],http://books.google.com/books?id=-HdbAAAAMAAJ&...
137261,137262,Letters of J R R Tolkien,[J.R.R. Tolkien],This collection will entertain all who appreci...,[biography and autobiography],https://play.google.com/store/books/details?id...
138961,138962,Tolkien and the Great War: The Threshold of Mi...,[John Garth],How the First World War influenced the author ...,[biography and autobiography],https://play.google.com/store/books/details?id...